### ISSUE TITLE
ARM Images

### ISSUE THREAD

**Issue by jzelinskie** [KohlsTechnology/prometheus_bigquery_remote_storage_adapter#308]
Thanks again for this project!

## What happens?

Image pull back-off when attempting to deploy to an ARM64 Kubernetes cluster

## What were you expecting to happen?

The adapter should spin up appropriately.

## Steps to reproduce: 

* Create a kind/k8s cluster on an ARM64 machine
* Install Prometheus Operator
* Apply manifest in the README

## Environment:

Kubernetes v1.27 on Linux ARM64

**Comment by vinny-sabatini** [comment]
Hi @jzelinskie thanks for the suggestion!

#312 should take care of providing Linux ARM64 images going forward. I'll create a release today so we can have "official" images rather than using the latest tag.

**Comment by vinny-sabatini** [comment]
v0.7.0 has been released with Linux ARM64 images - https://quay.io/repository/kohlstechnology/prometheus_bigquery_remote_storage_adapter?tab=tags
