### ISSUE TITLE
goreleaser should not tag latest directly

### ISSUE THREAD

**Issue by Smiley73** [KohlsTechnology/prometheus_bigquery_remote_storage_adapter#5]
## What happens?

Go releaser currently tags `latest` directly, which makes it show up under every release.

## What were you expecting to happen?

Have a separate `docker tag` command in the release code, to move the latest tag, but not have it show up in the release notes.

## Steps to reproduce: 
`make release`

**Comment by seanmalloy** [comment]
The release automation has been changed since this issues was originally created. This is no longer a problem.
